server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///studentmanager?serverTimezone=GMT%2B8
    username: root
    password: 456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    #前端控制
  thymeleaf:
    encoding: UTF-8
    cache: false


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
